import{i,S,a as b}from"./assets/vendor-f144e563.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function d(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=d(e);fetch(e.href,r)}})();const o={formSearch:document.getElementById("formSearch"),inputSearch:document.getElementById("inputSearch"),btnSearch:document.getElementById("btnSearch"),galleryList:document.querySelector(".js-ImagesCart"),loader:document.querySelector(".loader")};function h(){const t=o.inputSearch.value.trim(),a=o.inputSearch.placeholder;return t===""||t===a?(i.show({message:"Please, enter the name of the picture you are looking for",timeout:5e3,backgroundColor:"#a0cdde"}),o.btnSearch.disabled=!0,!1):(o.btnSearch.disabled=!1,!0)}o.inputSearch.addEventListener("focus",()=>{o.inputSearch.placeholder=""});o.inputSearch.addEventListener("blur",()=>{o.inputSearch.value.trim()===""&&(o.inputSearch.placeholder="Search images...")});const n={formSearch:document.getElementById("formSearch"),inputSearch:document.getElementById("inputSearch"),btnSearch:document.getElementById("btnSearch"),galleryList:document.querySelector(".js-ImagesCart"),loader:document.querySelector(".loader"),btnLoadMore:document.getElementById("btnLoadMore")};n.formSearch.addEventListener("submit",f);n.btnLoadMore.addEventListener("click",w);const L=new S(".js-ImagesCart a",{captionsData:"alt",captionDelay:250}),E="https://pixabay.com/api/",I="43910002-4f8293575df59775d1c0606c1";let l=1,g="";function f(t){t.preventDefault(),h()&&(g=n.inputSearch.value.trim(),n.galleryList.innerHTML="",n.loader.style.display="block",l=1,p())}async function p(){try{const a=(await b.get(E,{params:{key:I,q:g,image_type:"photo",orientation:"horizontal",safesearch:"true",lang:"en",page:l,per_page:15}})).data;return a.hits.length===0?i.show({message:"Sorry, there are no images matching your search query. Please, try again!",timeout:5e3,backgroundColor:"#EF4040"}):(l===1?n.galleryList.innerHTML=u(a.hits):n.galleryList.insertAdjacentHTML("beforeend",u(a.hits)),L.refresh()),a.hits}catch(t){console.error(t),i.show({message:"Something went wrong. Please, try again later.",timeout:5e3,backgroundColor:"#EF4040"})}finally{n.loader.style.display="none",n.formSearch.reset(),n.btnLoadMore.style.display="block"}}function u(t){return t.map(({webformatURL:a,largeImageURL:d,tags:c,likes:e,views:r,comments:s,downloads:y})=>`
          <li class="js-list">
              <a href="${d}"><img class="js-image" src="${a}" alt="${c}" /></a>
              <ul class="js-dates">
                  <li class="js-likes">Likes: ${e}</li>
                  <li class="js-views">Views: ${r}</li>
                  <li class="js-comments">Comments: ${s}</li>
                  <li class="js-downloads">Downloads: ${y}</li>
              </ul>
          </li>
      `).join("")}async function w(){l+=1;try{const t=await p();n.galleryList.insertAdjacentHTML("beforeend",u(t))}catch(t){console.error(t.message),i.show({message:"Something went wrong. Please, try again later.",timeout:5e3,backgroundColor:"#EF4040"})}}const m={formSearch:document.getElementById("formSearch"),inputSearch:document.getElementById("inputSearch"),btnSearch:document.getElementById("btnSearch"),galleryList:document.querySelector(".js-ImagesCart"),loader:document.querySelector(".loader")};m.formSearch.addEventListener("submit",void 0);m.inputSearch.addEventListener("input",h);m.btnSearch.addEventListener("click",f);
//# sourceMappingURL=commonHelpers.js.map
