import{a as g,S as p,i}from"./assets/vendor-f144e563.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const b="https://pixabay.com/api/",L="43910002-4f8293575df59775d1c0606c1";async function S(e,a,n){try{return(await g.get(b,{params:{key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",lang:"en",page:a,per_page:n}})).data}catch(s){throw console.error(s),s}}function u(e){return e.map(({webformatURL:a,largeImageURL:n,tags:s,likes:t,views:r,comments:l,downloads:f})=>`
          <li class="js-list">
              <a href="${n}"><img class="js-image" src="${a}" alt="${s}" /></a>
              <ul class="js-dates">
                  <li class="js-likes">Likes: ${t}</li>
                  <li class="js-views">Views: ${r}</li>
                  <li class="js-comments">Comments: ${l}</li>
                  <li class="js-downloads">Downloads: ${f}</li>
              </ul>
          </li>
      `).join("")}const o={formSearch:document.getElementById("formSearch"),inputSearch:document.getElementById("inputSearch"),btnSearch:document.getElementById("btnSearch"),galleryList:document.querySelector(".js-ImagesCart"),loader:document.querySelector(".loader"),btnLoadMore:document.getElementById("btnLoadMore"),loaderNoMore:document.querySelector(".loaderNoMore")};o.formSearch.addEventListener("submit",I);o.btnLoadMore.addEventListener("click",j);const w=new p(".js-ImagesCart a",{captionsData:"alt",captionDelay:250});let c=1,y="",d=0,m=0;function M(){return o.inputSearch.value.trim()===""?(i.show({message:"Please, enter a search query!",timeout:5e3,backgroundColor:"#EF4040"}),!1):!0}async function I(e){e.preventDefault(),M()&&(y=o.inputSearch.value.trim(),o.galleryList.innerHTML="",o.loader.style.display="block",o.loaderNoMore.style.display="none",o.btnLoadMore.style.display="none",d=0,c=1,await h())}async function h(){try{const e=await S(y,c,15);e.hits.length===0?(i.show({message:"Sorry, there are no images matching your search query. Please, try again!",timeout:5e3,backgroundColor:"#EF4040"}),o.btnLoadMore.style.display="none",o.loaderNoMore.style.display="none"):(d+=e.hits.length,m=e.totalHits,c===1?o.galleryList.innerHTML=u(e.hits):(o.galleryList.insertAdjacentHTML("beforeend",u(e.hits)),E()),w.refresh(),d>=m?(o.btnLoadMore.style.display="none",o.loaderNoMore.style.display="block",i.show({message:"We're sorry, but you've reached the end of search results.",timeout:5e3,backgroundColor:"#EF4040"})):o.btnLoadMore.style.display="block")}catch(e){console.error(e),i.show({message:"Something went wrong. Please, try again later.",timeout:5e3,backgroundColor:"#EF4040"})}finally{o.loader.style.display="none",o.formSearch.reset()}}function E(){const{height:e}=document.querySelector(".js-list").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}async function j(){c+=1,await h()}
//# sourceMappingURL=commonHelpers.js.map
